In [1]:
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  9.8091e-45],
        [ 6.6501e+31,  4.5758e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 1.5695e-43,  8.4898e-39,  1.0899e+18]])


In [3]:
x = torch.rand(5, 3)
x

tensor([[ 0.7849,  0.9664,  0.7601],
        [ 0.3493,  0.4305,  0.9119],
        [ 0.1876,  0.1862,  0.1366],
        [ 0.2647,  0.6356,  0.1830],
        [ 0.5439,  0.4863,  0.1361]])

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])

In [5]:
x = torch.tensor([5.5, 3])
x

tensor([ 5.5000,  3.0000])

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[-1.6403,  1.1971, -0.4962],
        [-1.0495, -1.3697, -2.4282],
        [-0.9506,  0.6242,  1.0519],
        [-0.1529, -0.4160, -1.1531],
        [ 0.2177, -1.0908, -1.6544]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
x + y

tensor([[-0.7992,  1.3026,  0.0037],
        [-0.6601, -1.0917, -1.9913],
        [-0.1539,  1.3686,  1.7373],
        [ 0.2789,  0.0400, -1.0006],
        [ 0.7340, -0.9576, -1.1110]])

In [10]:
torch.add(x, y)

tensor([[-0.7992,  1.3026,  0.0037],
        [-0.6601, -1.0917, -1.9913],
        [-0.1539,  1.3686,  1.7373],
        [ 0.2789,  0.0400, -1.0006],
        [ 0.7340, -0.9576, -1.1110]])

In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.7992,  1.3026,  0.0037],
        [-0.6601, -1.0917, -1.9913],
        [-0.1539,  1.3686,  1.7373],
        [ 0.2789,  0.0400, -1.0006],
        [ 0.7340, -0.9576, -1.1110]])


In [12]:
# add x to y
y.add_(x)
print(y)

tensor([[-0.7992,  1.3026,  0.0037],
        [-0.6601, -1.0917, -1.9913],
        [-0.1539,  1.3686,  1.7373],
        [ 0.2789,  0.0400, -1.0006],
        [ 0.7340, -0.9576, -1.1110]])


In [14]:
print(x)
print(x[:, 1])

tensor([[-1.6403,  1.1971, -0.4962],
        [-1.0495, -1.3697, -2.4282],
        [-0.9506,  0.6242,  1.0519],
        [-0.1529, -0.4160, -1.1531],
        [ 0.2177, -1.0908, -1.6544]])
tensor([ 1.1971, -1.3697,  0.6242, -0.4160, -1.0908])


In [18]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimension
print(x)
print(y)
print(z)
print(x.size(), y.size(), z.size())

tensor([[-0.3609, -0.0034, -0.2584,  0.3892],
        [-0.2731,  0.1862,  0.4108,  0.9518],
        [ 0.0093, -1.1317,  0.1834, -0.7645],
        [-0.8332,  1.3168, -2.2654, -2.9669]])
tensor([-0.3609, -0.0034, -0.2584,  0.3892, -0.2731,  0.1862,  0.4108,
         0.9518,  0.0093, -1.1317,  0.1834, -0.7645, -0.8332,  1.3168,
        -2.2654, -2.9669])
tensor([[-0.3609, -0.0034, -0.2584,  0.3892, -0.2731,  0.1862,  0.4108,
          0.9518],
        [ 0.0093, -1.1317,  0.1834, -0.7645, -0.8332,  1.3168, -2.2654,
         -2.9669]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.8267])
-0.8266995549201965


In [20]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


In [23]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(1, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


In [24]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device('cuda')    # a CUDA device object
    y = torch.ones_like(x, device=device)    # directly create a tensor on GPU
    x = x.to(device)    # or just use string ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([ 0.1733], device='cuda:0')
tensor([ 0.1733], dtype=torch.float64)
